networks:
  app-tier:
    driver: bridge
    
services: 
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        expose:
          - "3306"
        environment: 
            MYSQL_ROOT_PASSWORD: MYSQL_ALLOW_EMPTY_PASSWORD
            MYSQL_DATABASE: airtime
            MYSQL_USER: MYSQL_ROOT_PASSWORD
            MYSQL_PASSWORD: haOuh456+
        ports:
          - "3307:3306"    
        networks:
          - app-tier      
    
        volumes: 
            - ./init:/docker-entrypoint-initdb.d
    server:
        depends_on:
          - db
        build: ./
        restart: unless-stopped
        env_file: ./.env
        ports:
          - $NODE_LOCAL_PORT:$PORT
        environment:
          - DB_HOST=db
          - DB_USER=$DB_USER
          - DB_PASSWORD=$DB_PASSWORD
          - DB_NAME=$DB_NAME
          - DB_PORT=$DB_DOCKER_PORT
        stdin_open: true
        tty: true